name: build-test-deploy

on: push

jobs: 
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repo
        uses: actions/checkout@v3
      
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - run: npm run build
      
  test: 
    needs: build
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repo
        uses: actions/checkout@v3
      
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm ci

      - run: npm test

  deploy:
    needs: test
    permissions:
      contents: write
      pages: write     
      id-token: write  

    environment:
      name: production
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3
        with:
          static_site_generator: next

      - name: Install dependencies
        run: npm ci

      - run: npm run build

      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v1
        with: 
          path: "./out"

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v1
